import Exclude from '@/components/exclude';
import InactivityLockWrapper from '@/components/InactivityLockWrapper';
import { ThemeProvider } from "@/components/theme-provider";
import { AppProvider } from '@/context/AppContext';
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Moneycache",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AppProvider>
          <InactivityLockWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Exclude>
           {children}
         
          </Exclude>
          </ThemeProvider>
          </InactivityLockWrapper>
        </AppProvider>
      </body>
    </html>
  );
}